---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: voting-vote
    app.kubernetes.io/part-of: elections
    app.kubernetes.io/name: python
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: voting-vote
    app.kubernetes.io/version: "1.0"
  annotations:
    app.openshift.io/vcs-uri: "git@github.com:redhat-developer/topology-example.git"
    app.openshift.io/vcs-ref: "5207bbab97030890f2977ac317e02c2399af45a1"
  name: voting-vote
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: voting-vote
    app.kubernetes.io/part-of: elections
    app.kubernetes.io/name: python
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: voting-vote
    app.kubernetes.io/version: "1.0"
  annotations:
    app.openshift.io/vcs-uri: "git@github.com:redhat-developer/topology-example.git"
    app.openshift.io/vcs-ref: "5207bbab97030890f2977ac317e02c2399af45a1"
  name: voting-vote
spec:
  replicas: 1
  selector:
    app: voting-vote
    deploymentconfig: voting-vote
  strategy:
    activeDeadlineSeconds: 21600
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: voting-vote
        deploymentconfig: voting-vote
    spec:
      containers:
      - image: ' '
        imagePullPolicy: Always
        name: voting-vote
        ports:
        - containerPort: 8080
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      containerNames:
      - voting-vote
      from:
        kind: ImageStreamTag
        name: voting-vote:latest
    type: ImageChange
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: voting-vote
    app.kubernetes.io/part-of: elections
    app.kubernetes.io/name: python
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: voting-vote
    app.kubernetes.io/version: "1.0"
  annotations:
    app.openshift.io/vcs-uri: "git@github.com:redhat-developer/topology-example.git"
    app.openshift.io/vcs-ref: "5207bbab97030890f2977ac317e02c2399af45a1"
  name: voting-vote
spec:
  ports:
  - name: 8080-tcp
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: voting-vote
    deploymentconfig: voting-vote
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: voting-vote
    app.kubernetes.io/part-of: elections
    app.kubernetes.io/name: python
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: voting-vote
    app.kubernetes.io/version: "1.0"
  annotations:
    app.openshift.io/vcs-uri: "git@github.com:redhat-developer/topology-example.git"
    app.openshift.io/vcs-ref: "5207bbab97030890f2977ac317e02c2399af45a1"
  app: voting-vote
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: voting-vote
    weight: 100
