---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: voting-worker
    app.kubernetes.io/part-of: elections
    app.kubernetes.io/name: openjdk
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: voting-worker
    app.kubernetes.io/version: "1.0"
  annotations:
    app.openshift.io/vcs-uri: "git@github.com:redhat-developer/topology-example.git"
    app.openshift.io/vcs-ref: "5207bbab97030890f2977ac317e02c2399af45a1"
    app.openshift.io/connects-to: '["voting-vote","voting-result"]'
  name: voting-worker
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  labels:
    app: voting-worker
    app.kubernetes.io/part-of: elections
    app.kubernetes.io/name: openjdk
    app.kubernetes.io/component: backend
    app.kubernetes.io/instance: voting-worker
    app.kubernetes.io/version: "1.0"
  annotations:
    app.openshift.io/vcs-uri: "git@github.com:redhat-developer/topology-example.git"
    app.openshift.io/vcs-ref: "5207bbab97030890f2977ac317e02c2399af45a1"
    app.openshift.io/connects-to: '["voting-vote","voting-result"]'
  name: voting-worker
spec:
  replicas: 1
  selector:
    app: voting-worker
    deploymentconfig: voting-worker
  strategy:
    activeDeadlineSeconds: 21600
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        app: voting-worker
        deploymentconfig: voting-worker
    spec:
      containers:
      - image: ' '
        imagePullPolicy: Always
        name: voting-worker
      dnsPolicy: ClusterFirst
      restartPolicy: Always
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      containerNames:
      - voting-worker
      from:
        kind: ImageStreamTag
        name: voting-worker:latest
    type: ImageChange
